
import { Toaster } from "react-hot-toast";
import BootstrapClient from "./BootstrapClient";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <BootstrapClient />
         <Toaster />
        {children}
      </body>
    </html>
  );
}
